name: Setup WeChat Developer Tools
description: Install WeChat Developer Tools in the CI environment and load your project to run automated tests.
inputs:
  project-path:
    description: The root directory of your project, where project.config.json exists.
    default: '.'
  port:
    description: The port number of WebSocket endpoint of WeChat Developer Tools.
    default: 8888
  smtp-host:
    description: SMTP server to send Login QR Code
  smtp-port:
    description: SMTP port to send Login QR Code
  smtp-secure:
    description: Whether SMTPS is used
    default: false
  smtp-username:
    description: SMTP username to login the mail server
  smtp-password:
    description: SMTP password to login the mail server
  smtp-sender:
    description: Email address of the sender
  smtp-receiver:
    description: Email address of the receiver
runs:
  using: node12
  pre: build.js
  main: dist/index.js
