name: Setup WeChat Developer Tools

description: >
  Install WeChat Developer Tools in the CI environment and load your project to run automated tests.

branding:
  icon: upload
  color: green

inputs:
  cli:
    description: >
      The executable name of WeChat Developer Tools.
      The command will be installed and linked to cli.bat or ./cli in WeChat Developer Tools.
    default: wxdev

runs:
  using: node12
  main: dist/index.js
