name: Setup WeChat Developer Tools

description: >
  Install WeChat Developer Tools in the CI environment and load your project to run automated tests.
  As required by WeChat Developer Tools, it's necessary to login via WeChat (scanning a QR code).
  You'll need an SMTP server to send the QR code to your email address.

branding:
  icon: upload
  color: green

inputs:
  project-path:
    description: The root directory of your project, where project.config.json exists.
    default: '.'
  port:
    description: The port number of WebSocket endpoint of WeChat Developer Tools.
    default: 8888
  smtp-host:
    description: SMTP server to send Login QR Code
  smtp-port:
    description: SMTP port to send Login QR Code
  smtp-secure:
    description: Whether SMTPS is used
    default: false
  smtp-username:
    description: SMTP username to login the mail server
  smtp-password:
    description: SMTP password to login the mail server
  smtp-sender:
    description: Email address of the sender
  smtp-receiver:
    description: Email address of the receiver

runs:
  using: node12
  pre: build.js
  main: dist/index.js
