name: Setup WeChat Developer Tools

description: >
  Install WeChat Developer Tools in the CI environment and load your project to run automated tests.
  As required by WeChat Developer Tools, it's necessary to login via WeChat (scanning a QR code).
  You'll need an SMTP server to send the QR code to your email address.

branding:
  icon: upload
  color: green

inputs:
  cli:
    description: >
      The executable name of WeChat Developer Tools.
      The command will be installed and linked to cli.bat or ./cli in WeChat Developer Tools.
    default: wxdev

runs:
  using: node12
  pre: install.js
  main: dist/index.js
