name: Setup

on:
  push:
    branches:
      - canary
  pull_request:
    branches:
      - dev

jobs:
  setup:
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14.x
        os:
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup WeChat DevTools
      uses: ./

    - name: Run WeChat DevTools
      run: wxdev

    - name: Run WeChat DevTools (Windows Command Prompt)
      if: ${{ matrix.os == 'windows-latest' }}
      run: wxdev
      shell: cmd

    - name: Test a path with space
      run: |
        mkdir "a b"
        cd "a b"
        wxdev

  customized-setup:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Setup WeChat DevTools
      uses: ./
      with:
        version: 1052103200
        sha1sum: b72b1edff94d46177e5f0d452163bfea3dac16ca

    - name: Run WeChat DevTools
      run: wxdev

    - name: Run WeChat DevTools (Windows Command Prompt)
      run: wxdev
      shell: cmd

    - name: Test a path with space
      run: |
        mkdir "a b"
        cd "a b"
        wxdev
