name: Setup

on:
  push:
    branches:
      - canary
      - dev
  pull_request:
    branches:
      - dev

jobs:
  setup:
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup WeChat DevTools
      uses: ./

    - name: Run WeChat DevTools
      run: wxdev

    - name: Run WeChat DevTools (Windows Command Prompt)
      if: ${{ matrix.os == 'windows-latest' }}
      run: wxdev
      shell: cmd

    - name: Test a path with space
      run: |
        mkdir "a b"
        cd "a b"
        wxdev
