name: Setup

on:
  push:
    branches:
      - canary
      - dev
  pull_request:
    branches:
      - dev

jobs:
  setup:
    strategy:
      matrix:
        node-version: [14.x]
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: takashiro/setup-wechat-devtools@canary
      with:
        cli: wxd

    - name: Run WeChat DevTools
      run: echo 'y' | wxd quit
