name: Setup

on:
  push:
    branches:
      - canary
      - dev
  pull_request:
    branches:
      - dev

jobs:
  setup:
    strategy:
      matrix:
        node-version: [14.x]
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install
      run: npm ci --production
    - name: Setup WeChat DevTools
      uses: ./
      with:
        cli: wxd
    - name: Run WeChat DevTools
      run: wxd
