name: Setup

on:
  push:
    branches:
      - canary
      - dev
  pull_request:
    branches:
      - dev

jobs:
  setup:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        repository: takashiro/bezier-werewolf-wechat
        ref: e4cd8f53a62eff6648a4654280a1a4c1afc17f0e
        path: test-project

    - name: npm ci, build
      run: |
        npm ci
        npm run build
      working-directory: test-project

    - uses: takashiro/setup-wechat-devtools@canary
      with:
        project-path: test-project
        smtp-host: ${{ secrets.SMTP_HOST }}
        smtp-port: ${{ secrets.SMTP_HOST }}
        smtp-secure: true
        smtp-username: ${{ secrets.SMTP_USERNAME }}
        smtp-password: ${{ secrets.SMTP_PASSWORD }}
        smtp-sender: ${{ secrets.SMTP_SENDER }}
        smtp-receiver: ${{ secrets.SMTP_RECEIVER }}

    - name: npm test
      run: npm test
      working-directory: test-project
      env:
        CI: false
