name: Setup

on:
  push:
    branches:
      - canary
      - dev
  pull_request:
    branches:
      - dev

jobs:
  setup:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        repository: takashiro/bezier-werewolf-wechat
        ref: e4cd8f53a62eff6648a4654280a1a4c1afc17f0e

    - name: npm ci, build
      run: |
        npm ci
        npm run build

    - uses: takashiro/setup-wechat-devtools@canary

    - name: npm test
      run: npm test
